### ISSUE TITLE
Octave might be built from tarball of previous run

### ISSUE THREAD

**Issue by mmuetzel** [gnu-octave/octave-buildbot#15]
It looks like the tarball from previous runs isn't deleted after finishing to build. This can lead to the situation where that tarball is (inadvertently) used in the next run. That has happened on this run after the version numbers have been updated in the Octave repository:
https://buildbot.octave.space/#/builders/11/builds/367

It would probably be better to fail with a hard error if that is the case (like the builders on jwe's buildbot). It might be a good idea to delete the tarball from the worker when building has finished.

**Comment by siko1056** [comment]
Thanks for the notification.  Maybe the previous change might help in the future.
