### ISSUE TITLE
Show longer file names in download index

### ISSUE THREAD

**Issue by mmuetzel** [gnu-octave/octave-buildbot#3]
The names of the files on the download server are quite long. (That's not an issue per se.)
The index pages on octave.space truncate the file names after the first few characters. That makes it hard to identify the files.
![image](https://user-images.githubusercontent.com/65065102/95577345-43f98280-0a32-11eb-866a-08bc47e29637.png)

Index pages on other servers seem to be able to show the complete file names (e.g. http://repo.msys2.org/msys/x86_64/ ).

It would be nice if the indices on octave.space displayed the full file names.

I'm not sure if this is inside the scope of this repository. If it is not, feel free to close as invalid.

**Comment by siko1056** [comment]
Yeah, thanks for the motivation to look at this again. This was also annoying to me, too.  I use the apache2 webserver to serve those files on the Buildbot master.  Looking at it again, the fix was simple, by adding the option

```
IndexOptions NameWidth=*
```

https://webmasters.stackexchange.com/a/115248

Closing as fixed.
