### ISSUE TITLE
Some workers reliably fail on `sparse/eigs` with `make check`

### ISSUE THREAD

**Issue by siko1056** [gnu-octave/octave-buildbot#6]
See for example
- https://buildbot.octave.space/#/builders/5/builds/45 (worker 02)
- https://buildbot.octave.space/#/builders/5/builds/44 (worker 04)

Workers 01 and 03 are not affected.  Some facts
- worker 01 (CentOS 8.2, Intel(R) Core(TM) i5-6200U, 4 cores)
- worker 02 (CentOS 8.2, Intel(R) Xeon(R) CPU E5-2687W v4, 12 cores)
- worker 03 (CentOS 8.2, Intel(R) Xeon(R) CPU E5-2623 v4, 4 cores)
- worker 04 (CentOS 7.8, Intel(R) Xeon(R) Platinum 8276, 28 cores)

all run the worker image based on Ubuntu 18.04 with `podman`.

Some investigation did not bring much light into it.  Running on workers 02 and 04
```
./run-octave --eval "test eigs"
```
works without problems, while `make check` and extracting the command and running it manually fails.

The failing tests (there are several, after commenting out some) start here

https://hg.savannah.gnu.org/hgweb/octave/file/66b52ae69d73/scripts/sparse/eigs.m#l1379

Maybe a bug in (Octave calling) ARPACK under very certain conditions? :confused:

**Comment by mmuetzel** [comment]
If running `test eigs` on its own succeeds but `make check` fails reliably, there might be a series of commands that must be executed in a certain order to trigger the bug.
You might narrow down the necessary commands by successively removing some of the tests.
Unfortunately, I don't know a way to do that automatedly. You could use `runtests` to run all tests from a certain directory and then call `test eigs` and see if it triggers the bug.
When you found the directory, try to narrow it down to a certain file. After that to a certain test. Then, to certain commands.
When I tried to do that in the past, I tried a "bisect" approach by consecutively halving the number of tests (approximately) and continuing with the half that triggered the crash.
Let me know if you find a less manual way to do that.

**Comment by siko1056** [comment]
Thanks for the hint.  Yesterday I spent about an hour on this problem.  Debugging in this case is far less fun as on my local machine.  I have to login on the failing remote machine, inside a Docker container that has not even vim installed.  Additionally the error only occurs when running the verbose test suite (5 mins coffee break to receive the error) :dizzy_face:

I keep on working on this one.

**Comment by mmuetzel** [comment]
Dmitri's experience might be helpful:
https://octave.discourse.group/t/2nd-release-candidate-for-octave-6/309/3

IIUC, he had a similar issue when the used libraries linked to mixed ATLAS/OpenBLAS libraries. Maybe the issue here has the same cause.

**Comment by siko1056** [comment]
With the recent change 5d29c5460fb3672cc0891d79461c512bad9502ed I could build on both failing machines :smile:

Dmitri was right, it seems that the OpenBLAS, SuiteSparse, ARPACK-ng shipped with Ubuntu 18.04 is "not happy" with rather new server processors.  Now these libraries are self-compiled in the most recent version (ILP64) and seem to work.

Let's see if no further crashes appear :pray:  Closing report for now.

**Comment by mmuetzel** [comment]
Some of the buildbots seem to be failing because of mis-matched integer size (32bit and 64bit) of the BLAS libraries.
I'm not certain if this is because of a mis-configured build system. It might as well be that MXE Octave should build its own versions of native BLAS/LAPACK libraries...
See here: https://hg.octave.org/mxe-octave/file/tip/src/build-octave.mk#l27

IIUC, the OpenBLAS that is packaged with Ubuntu 18.04 is not compatible to the used hardware. Instead of compiling your own OpenBLAS, would it also be possible to use reference BLAS/LAPACK (and, e.g., not install OpenBLAS at all)?

**Comment by siko1056** [comment]
Yeah, today is not yet Friday 13th, but not very successful at all :sweat:

I noticed that the idea of merging my regular Docker builds with Buildbot was a bad idea.  Thanks, I'll try with reference BLAS and fall back to a modified version of my Docker builds without explicit 64 bit FORTRAN integers.  This might take a day, due to the enormous build times.  Sorry for the crashes.

**Comment by siko1056** [comment]
Alright, system seems to work again.  Thank you again for your idea with reference BLAS/LAPACK.  Recently I am struggling a lot with OpenBLAS that I totally lost this simple solution out of my sight.

Closing this report again :pray:
