### ISSUE TITLE
Worker cannot delete created `octave.jar` in volume, after the worker image has been updated

### ISSUE THREAD

**Issue by siko1056** [gnu-octave/octave-buildbot#7]
See <https://buildbot.octave.space/#/builders/5/builds/43>.

From inside the container with all workers one receives
```
rm: cannot remove 'build/scripts/java/octave.jar': Permission denied
```
you can only remove the file manually from outside the container, when navigating the the volume storage location.

I did not find any bug reports about this in Docker or Podman. :confused:

**Comment by mmuetzel** [comment]
Who owns that file when it cannot be deleted (by the buildbot user I guess)?

**Comment by siko1056** [comment]
In short: for simplicity uid 0 (root) creates that file inside the Docker container.

Using podman on CentOS 8.2, there are several players that give your problems:
1. SELinux https://www.redhat.com/sysadmin/user-namespaces-selinux-rootless-containers
2. Weird (for me) uid translations
3. More permission problems, when the container is started with user privileges, but the container user does not correspond with an existing user on the host :fire: :boom: More configuration effort for a potential worker :dizzy_face: 

Thus my strategy:  The container does not interact with the host system, only with volumes for storage, thus start container as root, run the builds with container root :innocent:

**Comment by siko1056** [comment]
Still occurs https://buildbot.octave.space/#/builders/8/builds/9, maybe the best will be to just remove the `octave.jar` at the end of the build :disappointed:
